"""Abstract device interfaces — all hardware drivers implement these."""

from __future__ import annotations

from abc import ABC, abstractmethod
from enum import Enum

import numpy as np


class TrackingRate(str, Enum):
    SIDEREAL = "sidereal"
    LUNAR = "lunar"
    SOLAR = "solar"
    KING = "king"


class PierSide(str, Enum):
    EAST = "east"
    WEST = "west"
    UNKNOWN = "unknown"


class FrameType(str, Enum):
    LIGHT = "light"
    BIAS = "bias"
    DARK = "dark"
    FLAT = "flat"


class AbstractMount(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def slew_to_ra_dec(self, ra_deg: float, dec_deg: float) -> None: ...
    @abstractmethod
    def slew_to_alt_az(self, alt_deg: float, az_deg: float) -> None: ...
    @abstractmethod
    def sync(self, ra_deg: float, dec_deg: float) -> None: ...
    @abstractmethod
    def park(self) -> None: ...
    @abstractmethod
    def unpark(self) -> None: ...
    @abstractmethod
    def abort(self) -> None: ...
    @abstractmethod
    def get_ra_dec(self) -> tuple[float, float]: ...
    @abstractmethod
    def get_alt_az(self) -> tuple[float, float]: ...
    @abstractmethod
    def is_tracking(self) -> bool: ...
    @abstractmethod
    def set_tracking(self, enabled: bool, rate: TrackingRate = TrackingRate.SIDEREAL) -> None: ...
    @abstractmethod
    def is_slewing(self) -> bool: ...
    @abstractmethod
    def is_parked(self) -> bool: ...
    @abstractmethod
    def get_side_of_pier(self) -> PierSide: ...


class AbstractCamera(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def expose(self, duration_s: float, frame_type: FrameType = FrameType.LIGHT) -> np.ndarray: ...
    @abstractmethod
    def abort_exposure(self) -> None: ...
    @abstractmethod
    def get_temperature(self) -> float: ...
    @abstractmethod
    def set_temperature(self, target_c: float) -> None: ...
    @abstractmethod
    def get_gain(self) -> int: ...
    @abstractmethod
    def set_gain(self, gain: int) -> None: ...
    @abstractmethod
    def get_binning(self) -> tuple[int, int]: ...
    @abstractmethod
    def set_binning(self, x: int, y: int) -> None: ...
    @abstractmethod
    def get_image_size(self) -> tuple[int, int]: ...
    @abstractmethod
    def get_pixel_size_micron(self) -> float: ...


class AbstractFocuser(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def get_position(self) -> int: ...
    @abstractmethod
    def move_to(self, position: int) -> None: ...
    @abstractmethod
    def move_by(self, steps: int) -> None: ...
    @abstractmethod
    def halt(self) -> None: ...
    @abstractmethod
    def is_moving(self) -> bool: ...
    @abstractmethod
    def get_max_position(self) -> int: ...
    def get_temperature(self) -> float | None:
        return None
    def get_step_size_micron(self) -> float | None:
        return None


class AbstractFilterWheel(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def get_position(self) -> int: ...
    @abstractmethod
    def set_position(self, slot: int) -> None: ...
    @abstractmethod
    def get_filter_names(self) -> list[str]: ...
    @abstractmethod
    def is_moving(self) -> bool: ...

    def set_filter(self, name: str) -> None:
        names = self.get_filter_names()
        if name not in names:
            raise ValueError(f"Filter '{name}' not in wheel: {names}")
        self.set_position(names.index(name))


class AbstractDome(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def open(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...
    @abstractmethod
    def is_open(self) -> bool: ...
    @abstractmethod
    def is_moving(self) -> bool: ...
    def park(self) -> None: ...
    def abort(self) -> None: ...
